# Generated by Django 6.0.4 on 2026-04-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_room_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort_name', models.CharField(default="Coorg Pristine Woods Hotel", max_length=200)),
                ('contact_email', models.EmailField(default='reservations@Pristine Woodspalace.com', max_length=254)),
                ('base_currency', models.CharField(default='CHF', max_length=10)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
