# Generated by Django 6.0.4 on 2026-04-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_globalsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
