# Generated by Django 6.0.4 on 2026-04-15 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_globalsetting_base_currency_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(help_text='e.g. 2 hours', max_length=50)),
                ('image_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('housekeeping', 'Housekeeping'), ('room_service', 'Room Service'), ('maintenance', 'Maintenance'), ('experience', 'Luxury Experience'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.experience'),
        ),
    ]
