# Generated by Django 6.0.4 on 2026-04-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_experience_alter_servicerequest_request_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='experiences',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='bookings.experience'),
        ),
    ]
