# Generated by Django 6.0.4 on 2026-04-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='housekeeping_status',
            field=models.CharField(choices=[('ready', 'Ready / Clean'), ('dirty', 'Dirty / Pending'), ('maintenance', 'Under Maintenance')], default='ready', max_length=20),
        ),
    ]
