# Generated by Django 6.0.4 on 2026-04-21 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_room_housekeeping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('housekeeping', 'Housekeeping'), ('supplies', 'Supplies'), ('concierge', 'Concierge'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_service_requests', to='bookings.room'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
