# Generated by Django 6.0.4 on 2026-04-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_servicerequest_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='extra_bed_price',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Additional price if guests exceed capacity', max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='total_inventory',
            field=models.PositiveIntegerField(default=1, help_text='Number of identical rooms available for this type'),
        ),
    ]
