# Generated by Django 6.0.4 on 2026-04-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_room_extra_bed_price_room_total_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='has_extra_bed',
            field=models.BooleanField(default=False),
        ),
    ]
